---

- hosts: all
  become: true
  tasks:
  - name: update repository index (Ubuntu)
    apt:
      update_cache: true
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - ../roles/common

- hosts: vdt_db
  become: true
  roles:
    - ../roles/vdt_db
    
- hosts: vdt_web
  become: true
  roles:
    - ../roles/vdt_web

- hosts: vdt_api
  become: true
  roles:
    - ../roles/vdt_api
  vars_files:
    - ../roles/vdt_api/vars/vault.yml
    - ../roles/vdt_api/vars/main.yml
  tags: 
    - vdt_backend