- name: Include vars
  include_vars:
    file: vars.yml
    
- name: Check if docker-compose.yml exists
  stat:
    path: /vdt-db/docker-compose.yml
  register: compose_file

- name: Run Docker Compose down
  shell: sudo docker compose down
  args:
    chdir: /vdt-db
  when: compose_file.stat.exists
    
- name: Remove directory
  file:
    path: /vdt-db          
    state: absent

- name: Create directory vdt-db
  file:
    path: /vdt-db     
    state: directory
    mode: '0755'

- name: Render Docker Compose template
  template:
    src: docker-compose.yml.j2
    dest: /vdt-db/docker-compose.yml


- name: Run Docker Compose up
  shell: sudo docker compose up -d
  args:
    chdir: /vdt-db